@baseUrl = http://localhost:3001

###
# @name generateToken
# Simulate token generation (mocked)
GET {{baseUrl}}/auth/fake-token

###
@token = {{generateToken.response.body.token}}

###
# @name heartbeat
GET {{baseUrl}}
